### ISSUE TITLE
Website Problems

### ISSUE THREAD

**Issue by jggunter** [GrayHay/StencilMC#2]
https://stencilmc.net/ Not loading logo, change title to "StencilMC" not just the domain.

<img src="http://share.sfxz.me/img/A4CZotXPKL.png">

**Comment by GrayHay** [comment]
Hi! Thank you for letting me know. I accidentally deleted the discord
channel that I was hosting the logo and images in. I am working to add
those back, and I am also taking into consideration your idea for moving
down the Join Stencil text and making the header bigger.

Thank you for your input!
-Grayson (GrayHay)
